Base-Name: ebcl_dev_container
Repository: ghcr.io/elektrobit
Base-Container: ubuntu:22.04
Version: v1.8.0-pre2
Version_packages: v1.8.0-pre2
Layers:
  - ../layers/base
  - ../layers/yocto
  - ../layers/pbuilder
  - ../layers/helper
  - ../layers/appdev
  - ../layers/build_tools
  - ../layers/vscode
  - ../layers/ebclfsa
  - ../layers/kernel
  - ../layers/squash
